name: openmm-dev
channels:
  - conda-forge
dependencies:
  - openmm
  - openff-toolkit
  - packmol
  - rdkit
  - ambertools
  - pip
  - scipy
  - nglview
  - mdtraj
  - openmmforcefields
  - mdanalysis
  - matplotlib